const mongoose = require('mongoose');
const mongoosePaginate = require('mongoose-paginate-v2');

const caseSchema = new mongoose.Schema(
    {
      caseId: {type: Number, default: null},
      caseTypCd: {type: String, trim: true, default: null},
      caseNbr: {type: String, trim: true, default: null},
      aplcId: {type: Number, default: null},
      primaryAddress: {type: String, trim: true, default: null},
      completionDt: {type: Date, default: null},
      filingDt: {type: String, trim: true, default: null},
      primaryCncDesc: {type: String, trim: true, default: null},
      caseNbrChgLog: {type: Array, default: null},
      encodedCaseId: {type: String, trim: true, default: null},
      primaryPin: {type: String, trim: true, default: null},
      primaryCnclDistNbr: {type: String, trim: true, default: null},
      admVisible: {type: Boolean, default: null},
      advisementEndDt: {type: Date, default: null},
      boeRefNbr: {type: Date, default: null},
      apelPrdEndDt: {type: Date, default: null},
      azaAsgnDt: {type: Date, default: null},
      caseDeemCmpltDt: {type: Date, default: null},
      caseOnHold: {type: String, trim: true, default: null},
      commContnuDt: {type: Date, default: null},
      commissionDt: {type: Date, default: null},
      commissionWaiveDt: {type: Date, default: null},
      completedFlg: {type: String, trim: true, default: null},
      cpReview: {type: String, trim: true, default: null},
      currentCaseStatus: {type: String, trim: true, default: null},
      dbaName: {type: String, trim: true, default: null},
      deirCirculationEndDate: {type: Date, default: null},
      deirCirculationStartDate: {type: Date, default: null},
      determination: {type: String, trim: true, default: null},
      eirNoticeCompletionDate: {type: Date, default: null},
      eirNoticePrepEndDate: {type: Date, default: null},
      eirNoticePrepStartDate: {type: Date, default: null},
      daysOverdue: {type: String, trim: true, default: null},
      envCaseFileRcvDt: {type: Date, default: null},
      envEirVisible: {type: Boolean, default: null},
      envFlg: {type: String, trim: true, default: null},
      envTerminationDate: {type: Date, default: null},
      environClrncDt: {type: Date, default: null},
      expeditedCaseFlg: {type: String, trim: true, default: null},
      fccDt: {type: String, trim: true, default: null},
      hearLocTxt: {type: String, trim: true, default: null},
      finalEirDistributionDate: {type: Date, default: null},
      hearingContnuDt: {type: Date, default: null},
      hearingDt: {type: Date, default: null},
      hearingTm: {type: String, trim: true, default: null},
      hearingWaiveDt: {type: Date, default: null},
      hearingWaivedFlg: {type: String, trim: true, default: null},
      holdDaysAfterFcc: {type: Number, default: null},
      holdDaysAfterLod: {type: Number, default: null},
      holdDaysBeforeAssigned: {type: String, trim: true, default: null},
      holdDaysBeforeFcc: {type: String, trim: true, default: null},
      holdDaysLodCea: {type: String, trim: true, default: null},
      holdDaysLodCp: {type: String, trim: true, default: null},
      incidentalFlg: {type: String, trim: true, default: null},
      isAppealed: {type: String, trim: true, default: null},
      isRbp: {type: Boolean, default: null},
      lastIncompleteDt: {type: Date, default: null},
      lodFlg: {type: String, trim: true, default: null},
      lodStartDt: {type: Date, default: null},
      lodToCeaDt: {type: Date, default: null},
      note: {type: String, trim: true, default: null},
      parntApelCntrNbr: {type: String, trim: true, default: null},
      processStartDt: {type: Date, default: null},
      projectDescription: {type: String, trim: true, default: null},
      pubDt: {type: Date, default: null},
      requestedEntitlement: {type: String, trim: true, default: null},
      scopingMeetingDate: {type: Date, default: null},
      stfAsgnDt: {type: Date, default: null},
      zaStfAsgnDt: {type: Date, default: null},
      cpa: {type: String, trim: true, default: null},
      environClrncNbr: {type: String, trim: true, default: null},
      geoNm: {type: String, trim: true, default: null},
      parntCaseId: {type: Number, default: null},
      apc: {type: String, trim: true, default: null},
      caseFileLocTxt: {type: String, trim: true, default: null},
      caseFileWhoTxt: {type: String, trim: true, default: null},
      representative: {type: String, trim: true, default: null},
      caseHearingDates: {type: Array, default: null},
      holdDays1: {type: Number, default: null},
      holdDays2: {type: Number, default: null},
      holdDays3: {type: Number, default: null},
      related_cases: {type: Array, default: null},
      propIds: [
        {type: mongoose.Schema.Types.ObjectId, ref: 'property', default: null},
      ],
      projectReference: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'project',
        default: null,
      },
      documents: [
        {type: mongoose.Schema.Types.ObjectId, ref: 'document', default: null},
      ],
      status: {type: String, trim: true, default: null},
    },
    {
      timestamps: true,
      // strict: false,
      toJSON: {virtuals: true}, // So `res.json()` and other `JSON.stringify()` functions include virtuals
      toObject: {virtuals: true}, // So `console.log()` and other functions that use `toObject()` include virtuals
    },
);

caseSchema.index({caseNbr: 1});

caseSchema.plugin(mongoosePaginate);

module.exports = mongoose.model('case', caseSchema);
